# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fjanisze/Code/simple_animation_engine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fjanisze/Code/simple_animation_engine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fjanisze/Code/simple_animation_engine/CMakeFiles /home/fjanisze/Code/simple_animation_engine/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fjanisze/Code/simple_animation_engine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named animation

# Build rule for target.
animation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 animation
.PHONY : animation

# fast build rule for target.
animation/fast:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/build
.PHONY : animation/fast

animation.o: animation.cpp.o
.PHONY : animation.o

# target to build an object file
animation.cpp.o:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/animation.cpp.o
.PHONY : animation.cpp.o

animation.i: animation.cpp.i
.PHONY : animation.i

# target to preprocess a source file
animation.cpp.i:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/animation.cpp.i
.PHONY : animation.cpp.i

animation.s: animation.cpp.s
.PHONY : animation.s

# target to generate assembly for a file
animation.cpp.s:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/animation.cpp.s
.PHONY : animation.cpp.s

animation_engine.o: animation_engine.cpp.o
.PHONY : animation_engine.o

# target to build an object file
animation_engine.cpp.o:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/animation_engine.cpp.o
.PHONY : animation_engine.cpp.o

animation_engine.i: animation_engine.cpp.i
.PHONY : animation_engine.i

# target to preprocess a source file
animation_engine.cpp.i:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/animation_engine.cpp.i
.PHONY : animation_engine.cpp.i

animation_engine.s: animation_engine.cpp.s
.PHONY : animation_engine.s

# target to generate assembly for a file
animation_engine.cpp.s:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/animation_engine.cpp.s
.PHONY : animation_engine.cpp.s

animation_text.o: animation_text.cpp.o
.PHONY : animation_text.o

# target to build an object file
animation_text.cpp.o:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/animation_text.cpp.o
.PHONY : animation_text.cpp.o

animation_text.i: animation_text.cpp.i
.PHONY : animation_text.i

# target to preprocess a source file
animation_text.cpp.i:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/animation_text.cpp.i
.PHONY : animation_text.cpp.i

animation_text.s: animation_text.cpp.s
.PHONY : animation_text.s

# target to generate assembly for a file
animation_text.cpp.s:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/animation_text.cpp.s
.PHONY : animation_text.cpp.s

animation_texture.o: animation_texture.cpp.o
.PHONY : animation_texture.o

# target to build an object file
animation_texture.cpp.o:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/animation_texture.cpp.o
.PHONY : animation_texture.cpp.o

animation_texture.i: animation_texture.cpp.i
.PHONY : animation_texture.i

# target to preprocess a source file
animation_texture.cpp.i:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/animation_texture.cpp.i
.PHONY : animation_texture.cpp.i

animation_texture.s: animation_texture.cpp.s
.PHONY : animation_texture.s

# target to generate assembly for a file
animation_texture.cpp.s:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/animation_texture.cpp.s
.PHONY : animation_texture.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/main.cpp.s
.PHONY : main.cpp.s

regression.o: regression.cpp.o
.PHONY : regression.o

# target to build an object file
regression.cpp.o:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/regression.cpp.o
.PHONY : regression.cpp.o

regression.i: regression.cpp.i
.PHONY : regression.i

# target to preprocess a source file
regression.cpp.i:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/regression.cpp.i
.PHONY : regression.cpp.i

regression.s: regression.cpp.s
.PHONY : regression.s

# target to generate assembly for a file
regression.cpp.s:
	$(MAKE) -f CMakeFiles/animation.dir/build.make CMakeFiles/animation.dir/regression.cpp.s
.PHONY : regression.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... animation"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... animation.o"
	@echo "... animation.i"
	@echo "... animation.s"
	@echo "... animation_engine.o"
	@echo "... animation_engine.i"
	@echo "... animation_engine.s"
	@echo "... animation_text.o"
	@echo "... animation_text.i"
	@echo "... animation_text.s"
	@echo "... animation_texture.o"
	@echo "... animation_texture.i"
	@echo "... animation_texture.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... regression.o"
	@echo "... regression.i"
	@echo "... regression.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

